### ISSUE TITLE
Wrong site area height detection

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#81] opened 2016-07-09 18:59 UTC
What I do and see:
1. go to https://trac.webkit.org/wiki/WebKit2
2. press End, it scrolls down correctly, scrolling indicator shows "Bot"
3. click on "Attachments" section, it pops-up with three options, scrolling indicator shows "102%"
4. press Home and then End, scrolling indicator shows "Bot", but it is not at the very bottom of the page
5. keep pressing Down (two times for me) until scrolled down to the bottom, scrolling indicator shows "102%"

What I see:

scrolling indicator shows >100% and End key does not scroll down to the bottom

What I expect:

scrolling indicator does never show >100%, End always scrolls down to the bottom

**Comment by aidanholm** [comment] 2016-07-10 07:23
Duplicate of #21, but I'll close that since this is a more detailed issue.

**Comment by ff2000** [comment] 2016-07-10 07:41
I already saw it the other way around: indicator never shows "Bot" but (e.g.) 39%, No chance to get Bot neither by `G` (End) nor by repeatedly pressing `j`.

**Comment by aidanholm** [comment] 2016-07-10 08:55
I've seen this too. Since there is no way to receive a notification when the document height changes, currently I monitor `DOMSubtreeModified` events and update the cached height on each event; the problem is caused by some document modifications not triggering an event.

I'm somewhat loath to poll the document height every _n_ milliseconds. Perhaps a hook on `DOMContentLoaded` would fix this _most_ of the time, but it's very hackish, and `DOMSubtreeModified` will already cause big performance issues for DOM modifications. An alternative would be to just do an IPC round trip every time you read the scroll position from Lua, removing the need for caching; round trips are already used elsewhere, and performance seems alright.

**Comment by aidanholm** [comment] 2016-07-13 17:48
Currently can't do an IPC round-trip as that requires blocking the UI process' main thread, which causes WebKit to deadlock. Ugh. Only way around that is to decouple the Lua state from the GTK state and run it on a separate thread, then block only the Lua thread while the main thread continues. Decoupling could also be useful for preventing UI freezes when running CPU-intensive Lua (e.g. syncing adblock state).

**Comment by aidanholm** [comment] 2016-07-25 10:16
I've given up on fixing the synchronous `webview.scroll` API for now; decoupling the Lua state and the webview would just cause a whole host of issues with deadlocks. I've instead pushed a JavaScript implementation of the scroll widget updater in `config/window.lua` at 3565048

**Closed as completed by aidanholm** 2016-07-25 10:16 UTC
Labels: bug
