### ISSUE TITLE
Running Lua JS functions in web process causes crashes for internal pages

### ISSUE THREAD

**Issue by donlzx** [aidanholm/luakit#399] opened 2017-06-14 15:21 UTC
Commit 505b04ca9c213fa026a5714500d1fe4d3ea7dc9b introduces the following regresssion:
```
Web process crashes when opening internal pages such as luakit://bookmarks
```
using Ubuntu Mate 16.04.2 LTS (Xenial Xerus) for Raspberry Pi 3 (armv7l)

Previous commit is fine.

Also, Luakit runs fine on Ubuntu 16.04 x86_64 versions.

**Comment by donlzx** [comment] 2017-06-14 15:37
This issues may be related to one or more of the following specific versions of libraries:
```
webkit2gtk = 2.16.3
libluajit = 2.0.4
libglib = 2.48.2
libgtk = 3.18.9
```

**Comment by aidanholm** [comment] 2017-06-14 16:59
Could you provide a stack trace / core dump? The appropriate binary is `/usr/lib/webkit2gtk-4.0/WebKitWebProcess`. Library versions look fine.

**Comment by donlzx** [comment] 2017-06-19 13:31
```
Thread 1 "WebKitWebProces" received signal SIGSEGV, Segmentation fault.
0x74c66b2e in JSC::JSGlobalObject::getOwnPropertySlot(JSC::JSObject*, JSC::ExecState*, JSC::PropertyName, JSC::PropertySlot&) ()
   from /usr/lib/arm-linux-gnueabihf/libjavascriptcoregtk-4.0.so.18
```
Is this error message helpful?

**Comment by aidanholm** [comment] 2017-06-21 06:21
A stack trace would be better, as it shows the point where luakit is calling javascriptcore and crashing.

**Comment by donlzx** [comment] 2017-06-26 14:36
Could you provide some brief instructions to get what you want? I'm not familiar with debugging the webkit stuffs.

**Comment by aidanholm** [comment] 2017-06-26 14:58
Sure:
1. First, disable the `view_source` module, as that opens a separate web process.
2. Run luakit with a single open tab.
3. Find the PID of the web process: `pgrep -f WebKitWebProcess` should return a single number.
4. Attach debugger to that web process: `sudo gdb -p PID`. You'll be greeted with a `(gdb)`: type "c" to continue.
5. Make it crash: in luakit, run `:open luakit://bookmarks`
6. In gdb, you should get a message about the crash and another `(gdb)` prompt: type "bt" to print a backtrace.
6. Copy and paste that here

**Comment by donlzx** [comment] 2017-06-27 12:30
Following the above procedure, I got the same result as posted before.  No more back trace results.

**Comment by donlzx** [comment] 2017-06-27 13:21
More on this bug:

* If open pages using ```:open luakit://help/```, webkit will crash
* If open pages in a new tab ```:tabopen luakit://help/```, webkit is fine

Something strange happens when reusing the current  webkit page, memory manangement related?

**Comment by aidanholm** [comment] 2017-06-28 03:36
I'm surprised that no backtrace is printed; that's odd. Could you please post the process limit you've set in `config/rc.lua`?

**Comment by donlzx** [comment] 2017-06-28 10:03
process limit set to default value:
```
luakit.process_limit = 0
```

**Comment by aidanholm** [comment] 2017-06-28 11:12
Does `luakit://help` crash? That page doesn't use the lua js function bridge. 
Also, @ds6 could you try the instructions above to get a Web process stack trace?

**Comment by donlzx** [comment] 2017-06-28 13:32
Yes, webkit crashes with ```:open``` command, but works fine with ```:tabopen``` command for all the following pages:
```
luakit://help
luakit://bookmarks
luakit://introspector
```
Tested with latest commit.

Maybe it a bug not related to JS funtions, but what other changes are included in the breaking commit?

**Comment by aidanholm** [comment] 2017-06-28 14:09
Actually I was wrong, all `luakit://` pages use the function bridge :/ There's no other changes introduced in that commit. Could you possibly upload a core dump of the WebKitWebProcess?

Edit: When you open the bookmarks page on a new tab, does the page work correctly? E.g. can you search for bookmarks / add bookmarks?

**Comment by donlzx** [comment] 2017-06-30 14:30
The bookmark page do have problems when opened on a new tab.

**Comment by sevmonster** [comment] 2017-07-01 00:13
Having some trouble with FreeBSD `gdb`. Some old bug that never got fixed.

**Comment by aidanholm** [comment] 2017-07-14 11:27
Sorry for the delay in responding!

@donlzx Then it's definitely a problem with how the Lua to JavaScript function bridge works. I'm trying to find a way to emulate a rpi3 so that I can reproduce this, without any success so far. I have a vm running 16.04.2 LTS, and luakit is working flawlessly, so I suspect that your architecture makes a difference.

@ds6 Any luck getting a strack trace?

**Comment by sevmonster** [comment] 2017-07-17 20:32
@aidanholm Not yet, I haven't had much time to myself since I got a new job.
gdb isn't cooperating, and I think it might be due to a broken world/package(s) rather than just broken gdb; I'm having more problems than initially expected (e.g. wine hanging when run under user accounts)
I'll recompile the kernel tomorrow since I have a day off.

_Sent from my Motorola Moto G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by aidanholm** [comment] 2017-07-18 14:11
No problem, and best of luck!

**Comment by ghost** [comment] 2017-07-19 22:52
@ds6: I had the same issues on FreeBSD 12-current. Compiling luakit with CC=gcc actually resolved the crash on internal pages.

**Comment by aidanholm** [comment] 2017-07-20 09:18
Great, I can reproduce this one now :) Thanks for the tipoff; should be fixed soon!

**Comment by aidanholm** [comment] 2017-07-20 11:00
Fixed at 33a47df3! There was a dependency on the order of evaluation of arguments of a function call; gcc did it one way, and clang did it the other way. Should work perfectly now :)

**Closed as completed by aidanholm** 2017-07-20 11:00 UTC
Labels: bug

**Comment by sevmonster** [comment] 2017-08-02 04:25
Sorry that I never got around to contributing, but I'm glad the issue has been resolved!
I will surely test it all out—when I get a chance to actually fix my apparently broken BSD install that I still haven't managed to resolve—as I have never actually seen the internal pages because of this bug.

_Sent from my Motorola Moto G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by aidanholm** [comment] 2017-08-02 05:06
@ds6 No problem! @xkpd3 has kindly packaged luakit for FreeBSD, so it should be pretty easy to use now!

**Comment by ghost** [comment] 2017-08-02 09:56
@ds6: It looks like the package has not reached 11-release yet. Check `/usr/ports/www/luakit`.
