### ISSUE TITLE
Unable to use compose key in insert mode

### ISSUE THREAD

**Issue by Ygrex** [aidanholm/luakit#78] opened 2016-07-09 17:33 UTC
What I do:
1. go to https://duckduckgo.com/
2. press 'i' entering insert mode
3. press compose key (AltGr in my case) and '<' two times

What I see:

nothing appears in the input field, but this warning in stderr of luakit:

*\* (luakit:4254): WARNING **: Error converting text from IM to UTF-8: Invalid byte sequence in conversion input

What I expect:

'«' appears in the input field as it works in any other application, no warnings

**Comment by aidanholm** [comment] 2016-07-10 07:18
I can't reproduce this; the same key sequence inserts '«' as expected. I'll see if it's possible to track down the source of that error.

**Comment by ff2000** [comment] 2016-07-10 07:48
Do you use a special input method like scim/ibus? I do not and I can't reproduce the issue.
Could you try epiphany and have a look if it shows the same issue? Then it might be webkit-gtk- related.

**Comment by aidanholm** [comment] 2016-07-10 07:53
Good idea; when using Fcitx, I can enter « in multiple GTK 3 programs---when quitting it, I cannot, and << appears. So it looks like this is a GTK issue.

**Comment by Ygrex** [comment] 2016-07-10 08:12
i'm using xim:
GTK_IM_MODULE=xim

probably specific to this method

**Comment by Ygrex** [comment] 2016-07-10 08:15
works as expected in epiphany 3.20.3-2

**Comment by aidanholm** [comment] 2016-07-14 19:11
Good catch; thanks for the PR. Issue fixed as of d02c2c7

**Closed as completed** 2016-07-14 19:10 UTC
Labels: bug
