### ISSUE TITLE
test fail

### ISSUE THREAD

**Issue by SolarAquarion** [aidanholm/luakit#397] opened 2017-06-12 15:34 UTC
luajit: error loading module 'tests.util' from file './tests/util.so':
        ./tests/util.so: undefined symbol: g_dir_make_tmp
stack traceback:
        [C]: at 0x00452b30
        [C]: in function 'require'
        tests/run_test.lua:15: in main chunk
        [C]: at 0x00404680
make: *** [Makefile:121: run-tests] Error 1

I'm doing a initial version of the check function of the pkgbuild

**Comment by aidanholm** [comment] 2017-06-12 22:38
Probably caused by an issue in the `tests/util.so` target in the Makefile, unless your GLib is < 2.30 (unlikely).

**Comment by SolarAquarion** [comment] 2017-06-15 15:53
let me try rebuild glib2

**Comment by SolarAquarion** [comment] 2017-06-16 00:21
that's weird

**Comment by SolarAquarion** [comment] 2017-06-16 00:35
i installed the git version of glib2

**Comment by aidanholm** [comment] 2017-06-16 01:46
My version is 2.52.2+9+g3245eba16-1

**Comment by aidanholm** [comment] 2017-07-01 13:30
Is this still a problem?

**Comment by aidanholm** [comment] 2017-08-10 02:50
Turned out to be a linker problem; this is fixed now with the merge of https://github.com/luakit/luakit/pull/418

**Comment by aidanholm** [comment] 2017-08-10 02:51
BTW I'm working on the luakit/luakit upstream repository now and will stop pushing to this one soon.

**Closed as completed by aidanholm** 2017-08-10 02:51 UTC
Labels: bug
