### ISSUE TITLE
luakit crashes:assertion 'wkCertificateInfo' failed

### ISSUE THREAD

**Issue by JR1994** [aidanholm/luakit#87] opened 2016-07-12 00:44 UTC
I have built luakit on my PowerBook G4 (gentoo ppc). When I launch browser I get a web process crashed error message. When I run luakit in gdb everytime it crashes I get this error:

*\* (luakit:8230): CRITICAL **: gboolean webkit_web_view_get_tls_info(WebKitWebView*, GTlsCertificate**, GTlsCertificateFlags*): assertion 'wkCertificateInfo' failed

**Comment by ff2000** [comment] 2016-07-12 05:02
When you are in gdb type `bt` to get the backtrace and post it here.

**Comment by JR1994** [comment] 2016-07-13 02:34
The browser does not segfaults it just gives an error when it tries to load the page and asks to reload. I keep reloading and I get the same error. Here is the full gdb output.

(gdb) run
Starting program: /usr/bin/luakit 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0xb7bff320 (LWP 9336)]
[New Thread 0xb71ff320 (LWP 9337)]
[New Thread 0xb69ff320 (LWP 9338)]
[New Thread 0xb61ff320 (LWP 9339)]
Stylesheet directory '/home/rican-linux/.local/share/luakit/styles/' doesn't exist, not loading user styles...
[New Thread 0xb51ff320 (LWP 9340)]
[New Thread 0xb49ff320 (LWP 9341)]
[New Thread 0xb41ff320 (LWP 9346)]
[New Thread 0xb39ff320 (LWP 9347)]
[New Thread 0xb31ff320 (LWP 9348)]
luakit web process: connecting to /home/rican-linux/.cache/luakit/socket
luakit web process: connected
luakit web process: Lua initializing...
luakit web process: Lua initialized
[Thread 0xb49ff320 (LWP 9341) exited]
luakit web process: ready for messages
[New Thread 0xb29ff320 (LWP 9365)]
[New Thread 0xb11ff320 (LWP 9376)]
[Thread 0xb31ff320 (LWP 9348) exited]
[New Thread 0xb31ff320 (LWP 9379)]
luakit web process: connecting to /home/rican-linux/.cache/luakit/socket
[Thread 0xb11ff320 (LWP 9376) exited]
luakit web process: connected
luakit web process: Lua initializing...
luakit web process: Lua initialized
luakit web process: ready for messages

*\* (luakit:9333): CRITICAL **: gboolean webkit_web_view_get_tls_info(WebKitWebView*, GTlsCertificate**, GTlsCertificateFlags*): assertion 'wkCertificateInfo' failed
[Thread 0xb29ff320 (LWP 9365) exited]
[New Thread 0xb29ff320 (LWP 9397)]
[New Thread 0xb09ff320 (LWP 9400)]
[Thread 0xb31ff320 (LWP 9379) exited]
[New Thread 0xb31ff320 (LWP 9402)]
luakit web process: connecting to /home/rican-linux/.cache/luakit/socket
[Thread 0xb09ff320 (LWP 9400) exited]
luakit web process: connected
luakit web process: Lua initializing...
luakit web process: Lua initialized
luakit web process: ready for messages

*\* (luakit:9333): CRITICAL **: gboolean webkit_web_view_get_tls_info(WebKitWebView*, GTlsCertificate**, GTlsCertificateFlags*): assertion 'wkCertificateInfo' failed
[Thread 0xb29ff320 (LWP 9397) exited]
[New Thread 0xb29ff320 (LWP 9418)]
[New Thread 0xb01ff320 (LWP 9420)]
[Thread 0xb31ff320 (LWP 9402) exited]
[New Thread 0xb31ff320 (LWP 9422)]
luakit web process: connecting to /home/rican-linux/.cache/luakit/socket
[Thread 0xb01ff320 (LWP 9420) exited]
luakit web process: connected
luakit web process: Lua initializing...
luakit web process: Lua initialized
luakit web process: ready for messages

*\* (luakit:9333): CRITICAL **: gboolean webkit_web_view_get_tls_info(WebKitWebView*, GTlsCertificate**, GTlsCertificateFlags*): assertion 'wkCertificateInfo' failed
[Thread 0xb41ff320 (LWP 9346) exited]
[Thread 0xb29ff320 (LWP 9418) exited]
[Thread 0xb39ff320 (LWP 9347) exited]
[Thread 0xb51ff320 (LWP 9340) exited]
[Thread 0xb61ff320 (LWP 9339) exited]
[Thread 0xb69ff320 (LWP 9338) exited]
[Thread 0xb71ff320 (LWP 9337) exited]
[Thread 0xb7bff320 (LWP 9336) exited]
[Thread 0xb7fb0240 (LWP 9333) exited]
[Inferior 1 (process 9333) exited normally](gdb) bt
No stack.

**Comment by aidanholm** [comment] 2016-07-13 09:31
Probably caused by webview `is_committed` flag not being updated. Fix pushed for that at dadcb45, but it's purely a cosmetic issue; actual behavior shouldn't change.

**Comment by aidanholm** [comment] 2016-07-13 13:59
Closing issue, since I haven't had this assertion fail since dadcb45. Feel free to reopen if it reoccurs.

**Closed as completed by aidanholm** 2016-07-13 13:59 UTC
