### ISSUE TITLE
No error message when luakit.so not found

### ISSUE THREAD

**Issue by SolarAquarion** [aidanholm/luakit#174] opened 2017-02-14 15:43 UTC
like the numbers to follow or letters

**Comment by aidanholm** [comment] 2017-02-14 16:18
Cannot reproduce with current `develop` branch (5f2a71b) and default config. Have you made any changes to your configuration? Are there any error messages in the log output? When you press `f` to enter follow mode, does the status bar become white with the prompt "Follow:"?

**Comment by SolarAquarion** [comment] 2017-02-14 16:19
Yes, that what happens

**Comment by aidanholm** [comment] 2017-02-14 16:25
What about the log; any error messages?

**Comment by SolarAquarion** [comment] 2017-02-14 16:29
No

**Comment by aidanholm** [comment] 2017-02-14 16:40
When you try to open a nonexistent web page, like `www.slkfjlkd.sdflhsdlfh`, there should be an error message. Is this error message at the top-left of the page, in black text on a white background?

**Comment by SolarAquarion** [comment] 2017-02-14 16:42
On Tue, Feb 14, 2017 at 11:40 AM, Aidan Holm <notifications@github.com>
wrote:

> www.slkfjlkd.sdflhsdlf



yes, it's in black test on a white background

**Comment by SolarAquarion** [comment] 2017-02-14 16:42
also h/j/k/l isn't working for me

**Comment by aidanholm** [comment] 2017-02-14 16:46
Ok, then the cause is that webkit cannot find the web extension `luakit.so`, which is needed for most functionality. I'll add a check that will produce an error message if this file isn't found.

**Comment by aidanholm** [comment] 2017-02-14 17:10
I've pushed an update (6f1e8ba) to check whether the `luakit.so` file exists. With this update, luakit will refuse to start without this file, and will print an error message describing where it should be.

I'm not sure how you're running luakit, so I'm not sure why this file would be missing for you.

**Comment by SolarAquarion** [comment] 2017-02-14 17:17
I built it from git and doing /usr/bin/luakit and make all

**Comment by aidanholm** [comment] 2017-02-14 17:24
You probably have development paths on. Run `make clean`, `DEVELOPMENT_PATHS=0 make`, then install

**Comment by SolarAquarion** [comment] 2017-02-14 17:29
that makes it work.  I use a Arch PKGBUILD

**Comment by aidanholm** [comment] 2017-02-14 17:32
Great! Could you post the link to the PKGBUILD?

**Comment by SolarAquarion** [comment] 2017-02-14 17:37
https://aur.archlinux.org/packages/luakit-git/

**Comment by aidanholm** [comment] 2017-02-14 19:25
Thanks for packaging; closing since this issue has been fixed

**Closed as completed by aidanholm** 2017-02-14 19:25 UTC
Labels: bug
