### ISSUE TITLE
Web process crashed

### ISSUE THREAD

**Issue by myf** [aidanholm/luakit#192] opened 2017-03-03 09:15 UTC
this might have been related to #189, freshly built luakit, while trying to connect to duckduckgo.com or github.com for example, will not load the page but instead `Web process crashed` will display on the page. There's no more information in the terminal, the only line recorded was: 

> [    1.568379] I: ./config/webview.lua:131: Requested link: https://github.com/ (text/html)

please confirm if anyone else has found similar behavior.

**Comment by aidanholm** [comment] 2017-03-03 11:45
Please post a stacktrace of `WebKitWebProcess`, if you can get one; I can't reproduce this on a649bd1.

**Comment by myf** [comment] 2017-03-05 07:34
@aidanholm there you go

https://gist.github.com/myf/9768cea1456bad914b04723575c1bfd6

**Comment by aidanholm** [comment] 2017-03-05 07:55
Does it crash consistently? This looks pretty normal; the main thread is doing some JavaScript work and the send thread is waiting for IPC to send. I'd guess that this is a WebKit bug.

**Comment by myf** [comment] 2017-03-05 08:03
yes this crashes consistently :(

**Comment by aidanholm** [comment] 2017-03-05 08:05
Does it also crash with other WebKit browsers, such as epiphany?

**Comment by myf** [comment] 2017-03-05 08:08
dwb doesn't crash on github but luakit does. hmmmm

**Comment by aidanholm** [comment] 2017-03-05 08:22
As far as I can see, dwb uses the WebKit1 API. Luakit uses the WebKit2 API.

**Comment by myf** [comment] 2017-03-05 08:33
i can try epiphany in a bit and report back.

i am using archlinux so whatever their version of webkitgtk2 is.

**Comment by aidanholm** [comment] 2017-03-05 08:36
Great, thanks. Presumably webkit2gtk 2.14.5-1 then, if you're up-to-date. That version works fine for me.

**Comment by myf** [comment] 2017-03-05 13:20
checked with epiphany, it cannot display github.com either. news.ycombinator.com is okay. same behavior as luakit. i am using webkit2gtk 2.14.5-1

**Comment by aidanholm** [comment] 2017-03-07 13:46
If epiphany and luakit both exhibit the same behavior, crash on the same pages, etc. then it's very likely a WebKit bug. In that case your options are limited. The best case is if it suddenly works again after an update to webkit2gtk.

**Comment by myf** [comment] 2017-03-07 14:16
it's what's happening now. i was just about to report back. things start to
work after gtk3 upate. related?

**Comment by aidanholm** [comment] 2017-03-07 14:22
So it's working again? Great! If updating gtk3 fixed it, it's unlikely to be related.

I'll close this issue; feel free to reopen if it resumes crashing again.

**Closed as completed by aidanholm** 2017-03-07 14:22 UTC

**Comment by myf** [comment] 2017-03-07 14:24
thanks! still mysterious but we are sure it's nothing luakit related
